@host = http://localhost:5207
@id = gondr
@pw = 123456

###############
## 유저 테스트들
###############

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "{{id}}",
  "nickname": "지태환",
  "password": "{{pw}}"
}
